[tool.poetry]
name = "openstates"
version = "2019.12"
description = ""
authors = ["James Turk <james@openstates.org>"]

[tool.poetry.dependencies]
python = "^3.7"
xlrd = "<2"
lxml = "^4.4"
pytz = "^2019.3"
feedparser = "^5.2"
python-dateutil = "^2.8"
spatula = "^0.0.2"
chardet = "^3.0"
suds-py3 = "^1.3"
SQLAlchemy = "^1.3"
opencivicdata = "^3.0"
requests = {version = "^2.22", extras = ["security"]}
mysqlclient = "^1.4.6"
openstates_metadata = "*"
pupa = "^0.10.1"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
